# Generated by Django 5.0.6 on 2024-07-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='origintal_price',
            new_name='original_price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='selling_pirce',
            new_name='selling_price',
        ),
    ]
